DROP TABLE customer_rewards PURGE;
/
CREATE TABLE customer_rewards (
    reward_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_email VARCHAR2(255),
    CONSTRAINT fk_customer_email FOREIGN KEY (customer_email) REFERENCES customers(email_address),
    gift_id NUMBER,
    CONSTRAINT fk_gift_id FOREIGN KEY (gift_id) REFERENCES gift_catalog(gift_id),
    reward_date DATE DEFAULT SYSDATE
);